# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shashank's Blog
email: shashank-prof-05@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I have added some contact information. Contact me if you find something inappropriate.
  Peace for everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shashank-prof-05.github.io" # the base hostname & protocol for your site
twitter_username: ProShanky
github_username:  shashank-pro-05
gems: [jekyll-paginate]
paginate:2 
paginate_path:"/archives/page/:num"
# Build settings
markdown: kramdown
